#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # No Color

echo -n '\n\n\n\n'
echo -n '############################\n'
echo -n 'Running pre-push hook...\n'
echo -n '############################\n\n'

echo -n '############################\n'
echo -n 'Running yarn lint...\n'
cd frontend
yarn lint
if [ $? -ne 0 ]; then
  echo "${RED}Please fix lint warnings and errors before pushing.${NC}"
  exit 1
fi
echo -n '############################\n\n'

echo -n '############################\n'
echo -n 'Running rubocop...\n'
cd ../backend
rubocop
if [ $? -ne 0 ]; then
  echo "${RED}Please fix rubocop warnings and errors before pushing.${NC}"
  exit 1
fi
echo -n '############################\n\n'

echo -n '############################\n'
echo -n 'Pre-push hook complete...\n'
echo -n '############################\n\n'

exit 0
