#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # No Color

echo '\n\n\n'
echo '############################'
echo 'Running pre-push hook...'
echo "############################\n"

echo '############################'
echo 'Running yarn lint...'
cd frontend
yarn lint
if [ $? -ne 0 ]; then
  echo "${RED}Please fix lint warnings and errors before pushing.${NC}\n"
  exit 1
fi
echo '############################\n'

echo '############################'
echo 'Running rubocop...'
cd ../backend
rubocop
if [ $? -ne 0 ]; then
  echo "${RED}Please fix rubocop warnings and errors before pushing.${NC}\n"
  exit 1
fi
echo '############################\n'

echo '############################'
echo 'Pre-push hook complete...'
echo '############################\n'

exit 0
