export const DEFAULT_COUPON_DENOMINATION = 10;

export const DEFAULT_SECONDARY_DONATION_VALUE = 10;

export const DATE_FORMAT = 'DD-MM-YYYY';

export const USER_FACING_DATE_FORMAT = 'DD MMM YYYY';

export const MAX_NUM_OF_CAMPAIGN_CHARITIES = 5;

export const MAX_IMAGE_SIZE_MB = 1;
