# To build a Docker image from this file, run from the root directory:
# docker build -f deployment/Dockerfile-frontend -t giving-coupons-frontend .

# Intermediate image for building the Next app
FROM node:16.13.0

# Environment variables
ENV APP_ROOT /frontend

# Copy source code into container
RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY frontend .

# Install dependencies
RUN yarn install --frozen-lockfile

# Build app
RUN yarn build

# Expose port
EXPOSE 3000

# Final image for running the Next app
CMD ["yarn", "start"]
