version: '3.8'

services:
  database:
    image: postgres
    container_name: giving-coupons-database
    restart: always
    volumes:
      - ~/db_data:/var/lib/postgresql/data
    networks:
      - giving-coupons-network
    logging:
      driver: journald
    expose:
      - '${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: ghcr.io/giving-coupons/giving-coupons-backend:latest
    container_name: giving-coupons-backend
    restart: always
    volumes:
      - ~/file_storage:/backend/storage
    depends_on:
      - database
    networks:
      - giving-coupons-network
    logging:
      driver: journald
    expose:
      - '4000'
    environment:
      RAILS_ENV: production
      PORT: 4000
      DB_HOST: giving-coupons-database
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: disable
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      MASTER_PASSWORD: ${MASTER_PASSWORD}

  frontend:
    image: ghcr.io/giving-coupons/giving-coupons-frontend:latest
    container_name: giving-coupons-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - giving-coupons-network
    logging:
      driver: journald
    expose:
      - '3000'

  nginx:
    image: ghcr.io/giving-coupons/giving-coupons-nginx:latest
    container_name: giving-coupons-nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - giving-coupons-network
    logging:
      driver: journald
    ports:
      - '80:80'
      - '443:443'

  certbot:
    image: certbot/certbot
    container_name: giving-coupons-certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - giving-coupons-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  giving-coupons-network:
